name: SimpleEvents
version: '1.4.1'
main: pl.pavetti.simpleevents.SimpleEvents
authors: [ 'Pavetti' ]
api-version: '1.13'
softdepend: ['Vault']
commands:
  sescore:
  simpleevent:
    aliases: ['se']
