name: SimpleEvents
version: '${project.version}'
main: pl.pavetti.simpleevents.SimpleEvents
authors: [ 'Pavetti' ]
api-version: '1.13'
softdepend: ['Vault']
commands:
  simpleevent:
    aliases: ['se']
