name: SimpleEvents
version: '1.5.4'
main: pl.pavetti.simpleevents.SimpleEvents
authors: [ 'Pavetti' ]
api-version: '1.20'
softdepend: ['Vault']
commands:
  scoreboardtoggle:
  simpleevent:
    aliases: ['se']
